- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Ansible version $ANSIBLE_TOWER!"
    - name: Set a Jenkins variable
      debug:
        msg: "JENKINS_EXPORT ANSIBLE_TOWER=3.4.2"
